Failure # 1 (occurred at 2020-11-24_16-00-03)
Traceback (most recent call last):
  File "C:\Users\imglt\Anaconda3\lib\site-packages\ray\tune\trial_runner.py", line 515, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "C:\Users\imglt\Anaconda3\lib\site-packages\ray\tune\ray_trial_executor.py", line 488, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "C:\Users\imglt\Anaconda3\lib\site-packages\ray\worker.py", line 1430, in get
    raise value
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.

